// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56LPtvr5c-bVNTtGC98B4tUU_CLVuAIY',
    appId: '1:870293495241:web:b29ec9c55789d1727cdc18',
    messagingSenderId: '870293495241',
    projectId: 'f-lc-tracker',
    authDomain: 'f-lc-tracker.firebaseapp.com',
    storageBucket: 'f-lc-tracker.appspot.com',
    measurementId: 'G-RN2FTGG21W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5MM_0mMcoNuvtlGUxNQY4pszBRS5t5w',
    appId: '1:870293495241:android:58b5563104d790507cdc18',
    messagingSenderId: '870293495241',
    projectId: 'f-lc-tracker',
    storageBucket: 'f-lc-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl_TOa5WxbNIZYkaqFiWjtOhhBfRROZFc',
    appId: '1:870293495241:ios:2645557eeb0dfec37cdc18',
    messagingSenderId: '870293495241',
    projectId: 'f-lc-tracker',
    storageBucket: 'f-lc-tracker.appspot.com',
    iosBundleId: 'com.example.fLcTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl_TOa5WxbNIZYkaqFiWjtOhhBfRROZFc',
    appId: '1:870293495241:ios:2645557eeb0dfec37cdc18',
    messagingSenderId: '870293495241',
    projectId: 'f-lc-tracker',
    storageBucket: 'f-lc-tracker.appspot.com',
    iosBundleId: 'com.example.fLcTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC56LPtvr5c-bVNTtGC98B4tUU_CLVuAIY',
    appId: '1:870293495241:web:263d3071a69d92367cdc18',
    messagingSenderId: '870293495241',
    projectId: 'f-lc-tracker',
    authDomain: 'f-lc-tracker.firebaseapp.com',
    storageBucket: 'f-lc-tracker.appspot.com',
    measurementId: 'G-WZ5NKZMX1R',
  );
}
